# Generated by Django 5.0 on 2023-12-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.data')),
            ],
        ),
    ]
